# Generated by Django 5.0.7 on 2024-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_email',
            new_name='otp',
        ),
    ]
