# Generated by Django 5.0.6 on 2024-07-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
    ]
