# Generated by Django 5.0.6 on 2024-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_is_verified_user_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='otp_email',
        ),
    ]
